// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TodoWebAPI.Data;

namespace TodoWebAPI.Migrations
{
    [DbContext(typeof(TodoWebAPIContext))]
    [Migration("20210506045029_AddNavigation")]
    partial class AddNavigation
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TodoWebAPI.Data.TodoItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("priorityTypeId")
                        .HasColumnType("int");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("priorityTypeId");

                    b.ToTable("TodoItem");
                });

            modelBuilder.Entity("TodoWebAPI.Data.TodoPriorityType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("todoPriorityType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("TodoPriorityType");
                });

            modelBuilder.Entity("TodoWebAPI.Data.TodoItem", b =>
                {
                    b.HasOne("TodoWebAPI.Data.TodoPriorityType", "priorityType")
                        .WithMany()
                        .HasForeignKey("priorityTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("priorityType");
                });
#pragma warning restore 612, 618
        }
    }
}
